// Generated by gencpp from file maru2_msgs/ControlInput.msg
// DO NOT EDIT!


#ifndef MARU2_MSGS_MESSAGE_CONTROLINPUT_H
#define MARU2_MSGS_MESSAGE_CONTROLINPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace maru2_msgs
{
template <class ContainerAllocator>
struct ControlInput_
{
  typedef ControlInput_<ContainerAllocator> Type;

  ControlInput_()
    : header()
    , forward(0.0)
    , left(0.0)  {
    }
  ControlInput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , forward(0.0)
    , left(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _forward_type;
  _forward_type forward;

   typedef double _left_type;
  _left_type left;





  typedef boost::shared_ptr< ::maru2_msgs::ControlInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maru2_msgs::ControlInput_<ContainerAllocator> const> ConstPtr;

}; // struct ControlInput_

typedef ::maru2_msgs::ControlInput_<std::allocator<void> > ControlInput;

typedef boost::shared_ptr< ::maru2_msgs::ControlInput > ControlInputPtr;
typedef boost::shared_ptr< ::maru2_msgs::ControlInput const> ControlInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maru2_msgs::ControlInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maru2_msgs::ControlInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maru2_msgs::ControlInput_<ContainerAllocator1> & lhs, const ::maru2_msgs::ControlInput_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.forward == rhs.forward &&
    lhs.left == rhs.left;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maru2_msgs::ControlInput_<ContainerAllocator1> & lhs, const ::maru2_msgs::ControlInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maru2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maru2_msgs::ControlInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maru2_msgs::ControlInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maru2_msgs::ControlInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maru2_msgs::ControlInput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maru2_msgs::ControlInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maru2_msgs::ControlInput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maru2_msgs::ControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "856bf47abb59b5d1915d43dbdc570b1b";
  }

  static const char* value(const ::maru2_msgs::ControlInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x856bf47abb59b5d1ULL;
  static const uint64_t static_value2 = 0x915d43dbdc570b1bULL;
};

template<class ContainerAllocator>
struct DataType< ::maru2_msgs::ControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maru2_msgs/ControlInput";
  }

  static const char* value(const ::maru2_msgs::ControlInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maru2_msgs::ControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Simple message to communicate intended control. Relayed by middleman.\n"
"\n"
"Header header       # Reference shenanigans\n"
"\n"
"float64 forward     # forward raw control input\n"
"float64 left        # left raw control input\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::maru2_msgs::ControlInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maru2_msgs::ControlInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.forward);
      stream.next(m.left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maru2_msgs::ControlInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maru2_msgs::ControlInput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "forward: ";
    Printer<double>::stream(s, indent + "  ", v.forward);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARU2_MSGS_MESSAGE_CONTROLINPUT_H
